### PR TITLE
wip: Dependency upgrades

### PR DESCRIPTION
**Pull request by haganbmj**
Frankly I don't know how the typescript setup on here is configured.
There appears to be a version mismatch occurring somewhere, which I originally thought was to do with either forcing es6 or explicitly targeted Typescript 3.1.
Apparently the ts tests can also fail while still passing the build, so that's another issue to go work out.
This currently builds the type definitions correctly, but fails their tests.

### CODE REVIEW

**Comment by rodrigograca31** [comment]
Seems you started doing what I was about to try to do because you got many dependencies outdated.

This is the output of [ncu](https://www.npmjs.com/package/npm-check-updates): 
image

red indicates a major version is available. 
seems you are bumping to minor versions only. I was about to bump to major ones...

**Comment by haganbmj** [comment]
Yeah, I scaled down the initial set of version bumps to try and track down the failure. Once I correct that I can actually start applying the rest, including the majors.

**Comment by rodrigograca31** [comment]
Yeah, the best thing would be to bump everything to the latest eventually...

**Comment by rodrigograca31** [comment]
Btw, I dont know why but if I run `npm run test:types` on your branch if fails with a bunch of errors... but here on the PR page I see everything is green......... 🤔

**Comment by rodrigograca31** [comment]
@haganbmj Hi!

Do you have an eta on when you will merge this? 🤔

**Comment by Niek** [comment]
@haganbmj another +1 from me :)

**Pull request closed without merging**
