### PR TITLE
Adding handshakeTimeout support for Socket connect

### PR DESCRIPTION
**Pull request by olafurw**
### Description:
User can now provide timeout: [somenumber] as a connection attribute alongside address and password. This was needed because of intermittent connection problems and reconnection and the default timeout timer was too long.

### CODE REVIEW

**Comment by Lange** [comment]
Thanks for this PR! It looks like it is failing the lint step on CI. Can you fix the issues reported by the linter?

**Comment by Lange** [comment]
Thanks, looks like the remaining error is in the CI process itself. I'll try to take a look today. Please remind me if I haven't gotten to it in the next couple days.

**Comment by olafurw** [comment]
Cheers.

**Comment by haganbmj** [comment]
I'd rather just leave it open ended and do something like this where all of the unnecessary args are passed on to the underlying WebSocket.

```
obs.connect({
 address: 'localhost:4444',
 handshakeTimeout: 1000,
 whateverElse: 1
})
```

That said, I need to sit down and just double check that this isn't a browser versus node compatibility issue. I'm seeing different constructors, but maybe isomorphic-ws can help with that too.

https://www.npmjs.com/package/ws
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket

**Comment by olafurw** [comment]
Want me to PR it or are you going to look at it? I'd actually prefer the options separately since they could overlap with features in this lib.

**Pull request closed without merging**
